import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { RefreshCw, Coins, ArrowRightLeft } from 'lucide-react';
import SEO from '../components/SEO';

export default function CarbonFinance() {
  return (
    <>
      <SEO title="Carbon Stream Financing" description="Innovative financing for carbon project development." />
      
      {/* --- HERO SECTION --- */}
      <div className="relative min-h-[80vh] flex items-center justify-center bg-silver-dark text-white pacaembu-font overflow-hidden">
        <div className="absolute inset-0 z-0">
          <img 
            src="/af2.jpg" 
            alt="Financial Growth" 
            className="w-full h-full object-cover opacity-20"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-silver-dark/90 via-silver-dark/80 to-transparent" />
        </div>

        <div className="container mx-auto px-6 relative z-10 pt-20">
          <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>
            <div className="flex items-center gap-2 text-silver-blue font-bold text-sm tracking-wider uppercase mb-4">
                <Link to="/services" className="hover:text-white transition-colors">Services</Link> / Carbon Finance
            </div>
            <h1 className="text-5xl md:text-6xl font-display font-bold mb-6">Carbon Streaming</h1>
            <p className="text-xl text-slate-300 max-w-3xl leading-relaxed">
              Provision of financing for development of carbon projects in exchange for a stream of future cashflows.
            </p>
          </motion.div>
        </div>
      </div>

      {/* --- MAIN CONTENT --- */}
      <section className="py-24 bg-white pacaembu-font">
        <div className="container mx-auto px-6">
          <div className="max-w-5xl mx-auto">
            
            {/* 3-Step Process Grid */}
            <div className="grid md:grid-cols-3 gap-8 mb-20">
                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.1 }}
                  className="text-center p-8 bg-slate-50 rounded-3xl border border-slate-100 hover:shadow-xl transition-all hover:-translate-y-1"
                >
                    <div className="w-16 h-16 bg-white rounded-2xl mx-auto flex items-center justify-center text-silver-green mb-6 shadow-sm border border-slate-100"><Coins size={32} /></div>
                    <h3 className="font-bold text-slate-900 mb-3 text-lg">1. Upfront Deposit</h3>
                    <p className="text-slate-600 text-sm leading-relaxed">Cash or shares provided to the project partner to fund initial development phases.</p>
                </motion.div>

                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.2 }}
                  className="text-center p-8 bg-slate-50 rounded-3xl border border-slate-100 hover:shadow-xl transition-all hover:-translate-y-1"
                >
                    <div className="w-16 h-16 bg-white rounded-2xl mx-auto flex items-center justify-center text-silver-blue mb-6 shadow-sm border border-slate-100"><RefreshCw size={32} /></div>
                    <h3 className="font-bold text-slate-900 mb-3 text-lg">2. Delivery Rights</h3>
                    <p className="text-slate-600 text-sm leading-relaxed">Silver Carbon receives rights to purchase future credits generated by the project.</p>
                </motion.div>

                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.3 }}
                  className="text-center p-8 bg-slate-50 rounded-3xl border border-slate-100 hover:shadow-xl transition-all hover:-translate-y-1"
                >
                    <div className="w-16 h-16 bg-white rounded-2xl mx-auto flex items-center justify-center text-indigo-500 mb-6 shadow-sm border border-slate-100"><ArrowRightLeft size={32} /></div>
                    <h3 className="font-bold text-slate-900 mb-3 text-lg">3. Ongoing Payments</h3>
                    <p className="text-slate-600 text-sm leading-relaxed">Purchase price paid when credits are sold, with funds flowing back to communities.</p>
                </motion.div>
            </div>

            {/* Explanation Section */}
            <div className="bg-silver-dark text-white p-10 md:p-16 rounded-[2.5rem] relative overflow-hidden shadow-2xl">
                <div className="absolute top-0 right-0 w-96 h-96 bg-silver-blue/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3" />
                <div className="relative z-10">
                  <h3 className="text-3xl font-display font-bold mb-6">Why Stream Financing?</h3>
                  <p className="text-slate-300 mb-10 leading-relaxed text-lg max-w-3xl">
                      A carbon credit stream is a contractual agreement whereby Silver Carbon, as the stream purchaser, makes an upfront deposit to a project partner in return for the right to purchase all or a portion of the future carbon credits. This allows the project partner to fund the development, expansion, or operation of the project without traditional debt burdens.
                  </p>
                  <Link to="/contact">
                      <button className="px-10 py-4 bg-white text-slate-900 rounded-full font-bold hover:bg-silver-green hover:text-white transition-all shadow-lg hover:shadow-silver-green/20">
                          Apply for Financing
                      </button>
                  </Link>
                </div>
            </div>
            
          </div>
        </div>
      </section>
    </>
  );
}